[package]
name = "check-broken-packages"
version = "0.1.0"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
ansi_term = "0.11"
crossbeam = "0.7.1"
indicatif = "0.11.0"
log = { version = "0.4", features = ["max_level_off", "release_max_level_off"] }
num_cpus = "1.10.0"
simple_logger = { version = "1.2.0", default-features = false }

[dev-dependencies]
tempdir = "0.3.7"
