[package]
name = "check-broken-packages"
version = "0.1.0"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
crossbeam = "0.7.1"
log = { version = "0.4", features = ["max_level_off", "release_max_level_off"] }
simple_logger = { version = "1.2.0", default-features = false }
num_cpus = "1.10.0"

[dev-dependencies]
tempdir = "0.3.7"
