[package]
name = "check-broken-packages"
version = "0.1.0"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
crossbeam = "0.7.1"
log = "0.4"
num_cpus = "1.10.0"

[dev-dependencies]
tempdir = "0.3.7"
